### ISSUE TITLE
Download Count not working properly

### ISSUE THREAD

**Issue by f-fuchs** [kefir500/ghstats#6]
Hey,
when I try to get the stats of the repository qkitgroup/qkit the download count shows 0 even though I too downloaded the repository, which should make it 1 at least, even in the unlikely case the repo really had 0 downloads.
Link to the repository:
https://github.com/qkitgroup/qkit/tree/stable
I tried:
ghstats qkitgroup qkit
ghstats qkitgroup/qkit
ghstats qkitgroup qkit -d 
When I try it with atom it shows a download count of 1430252 which should mean the program still works but why does it not work with the desired repo?

**Comment by kefir500** [comment]
The `qkitgroup/qkit` [releases](https://github.com/qkitgroup/qkit/releases) don't contain any downloadable assets except for the source code zip/tar.gz archives. GitHub API doesn't provide download stats for those.

**Comment by torbjone** [comment]
Hi, I am trying to find the number of clones and downloads for https://github.com/LFPy/LFPy, but it looks like I have the same problem as above. Is there any way around this, or is the information just not available?

**Comment by kefir500** [comment]
Hi @torbjone, see my previous comment:
Unfortunately, GitHub API doesn't provide download stats for the source code assets.
